name: Build and upliad artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v -o hypr-zoom ./hypr-zoom.go  # Specify the output binary name

    - name: Delete Previous artifact
      uses: geekyeggo/delete-artifact@v5
      with:
          name: hypr-zoom
          failOnError: false

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hypr-zoom  
        path: hypr-zoom  
